{
  "token": "977345033:AAHF1uP4aKlQedE25kGg8Vj5Z6jZpcfX5Kg",
  "domain": "https://www.vallotta-party-bot.com",
  "url": "https://api.telegram.org/bot",
  "username": "VallottaCinemaBot",
  "first_name": "vallotta-cinema",
  "idBot": "977345033",
  "commanads": [
    "/find",
    "/cerca",
    "/movie",
    "/series"
  ]
}
first 0
init 0
ERROR "IndexError" in showEpisodeUrl for index[17]
 0) Chernobyl
 1) Chernobyl Diaries. La Mutazione 2012
 2) Chernobyl Diaries - La Mutazione
Traceback (most recent call last):
  File "bot_no_webhook.py", line 36, in <module>
    bot.run()
  File "/root/bot.py", line 40, in run
    self._dispatchAction(update)
  File "/root/bot.py", line 54, in _dispatchAction
    self.cinema.dispatchAction(Update(update))
  File "/root/botvallottacinema.py", line 61, in dispatchAction
    message = Message(update.message)
  File "/root/telegram.py", line 37, in __init__
    self.message_id: int = message['message_id']
TypeError: 'NoneType' object is not subscriptable
{
  "token": "977345033:AAHF1uP4aKlQedE25kGg8Vj5Z6jZpcfX5Kg",
  "domain": "https://www.vallotta-party-bot.com",
  "url": "https://api.telegram.org/bot",
  "username": "VallottaCinemaBot",
  "first_name": "vallotta-cinema",
  "idBot": "977345033",
  "commanads": [
    "/find",
    "/cerca",
    "/movie",
    "/series"
  ]
}
first 515620839
init 515620840
Traceback (most recent call last):
  File "/root/telegram.py", line 38, in __init__
    self.message_id: int = message['message_id']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot_no_webhook.py", line 36, in <module>
    bot.run()
  File "/root/bot.py", line 40, in run
    self._dispatchAction(update)
  File "/root/bot.py", line 54, in _dispatchAction
    self.cinema.dispatchAction(Update(update))
  File "/root/botvallottacinema.py", line 61, in dispatchAction
    message = Message(update.message)
  File "/root/telegram.py", line 41, in __init__
    f.write(message)
TypeError: write() argument must be str, not None
